### ISSUE TITLE
Some changes not picked up on module reload

### ISSUE THREAD

**Issue by CodeReclaimers** [nturley/synthia#1]
First of all, thanks for making this available!  I had previously installed the toolchain for ICEStick, so synthia worked right out of the box for me.  Having a "go button" for quick experiments is really handy.

One minor issue I ran into is that the Python module import/reload machinery apparently pays no mind to certain changes. For example, if I modify the body of the locally-defined `drive_leds` function in the rotate example, deploy, then make another change to the same function, the second (and all subsequent) modifications do not make it into /tmp/top.v.

I was able to get around this by modifying `_conversion.verilogify` to open a fresh child Python process to do the import and toVerilog call, so that the process is consistent.  My change feels a bit hackish, but I could try to clean it up and make a pull request if you'd like.

**Comment by nturley** [comment]
I'm glad it was useful.

Yeah, I remember there being a problem with refreshing. I thought I remember fixing it but apparently not. A PR would be appreciated.

**Comment by CodeReclaimers** [comment]
I think this is something the Python machinery itself doesn't do correctly, but I'm not entirely sure.  I should be able to make some time to clean it up and make a PR by the weekend.

**Comment by CodeReclaimers** [comment]
Thanks for including this!
