### ISSUE TITLE
Item for your ToDo list

### ISSUE THREAD

**Issue by pcotret** [nturley/synthia#2]
I just got a new laptop with Lubuntu 15.10. Here is my script to install your tool with all dependencies:
# On a fresh Lubuntu 15.10.
# apt-get some packages :)

sudo apt-get install git python-pip clang libftdi-dev gawk tcl-dev libreadline-dev bison flex mercurial gir1.2-gtksource-3.0
# install icestorm

cd $HOME
git clone https://github.com/cliffordwolf/icestorm.git icestorm
cd icestorm && make && sudo make install
# arachne-pnr

cd $HOME
git clone https://github.com/cseed/arachne-pnr.git arachne-pnr
cd arachne-pnr && make && sudo make install
# install yosys

cd $HOME
git clone https://github.com/cliffordwolf/yosys.git yosys
cd yosys && make && sudo make install

Hope this helps ;)

**Comment by nturley** [comment]
Thanks. I dropped your instructions into the readme.
